name: update_issue

on:
  schedule:
    - cron: '0 11 * * *' # This is the argument for set sending period. You can refer to https://crontab.guru and edit it there.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Install requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run python
      run: |
        python run.py
      env:
        token : ${{ secrets.MY_GITHUB_TOKEN }} # You MUST SET SECRET ENVIRONMENTS. Do NOT Change This.
        organization: 'Arxiv-Sender' # You MUST SET HERE to same as this organization.
        repository: 'Arxiv-Sender' # You MUST SET HERE to same as this repository.
        search_limitation: '9999' # This is the number of papers to search. Feel free to change it, but the larger the better.
        send_limitation: '100' # This is the limit on the number of papers to upload per email.
        send_term: '1' # This will determine how up-to-date your paper should be sent.
        abstract: 'False' # Type False for enable abstract in email
